make acrylamid/defaults/ a package (again)
'acrylamid/defaults/' is used as a package in various places.
But python needs the file '__init__.py' in the root directory of the
package.
Commit '7826fa16' moved this file away. Acrylamid keeps working if there
is a old '__init__.pyc', generated from an old '__init__.py'. But
otherwise it crashes with:
'ImportError: cannot import name defaults'

This commit adds an empty '__init__.py' to make python recognize the
package again.
(Compare http://docs.python.org/tutorial/modules.html#packages , first
big paragraph after the first listing)